[project]
name = "healthcare-analytics-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "veerkumarmodi", email = "veerkumamrmodi76@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
healthcare-analytics-agent = "healthcare_analytics_agent:main"

[build-system]
requires = ["uv_build>=0.11.19,<0.12.0"]
build-backend = "uv_build"
