from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd

from ..config.paths import Paths
from ..config.logging_config import get_logger


class BaseService:
    """
    Base class for all AI-AIP services.

    Provides:

    - Logger
    - JSON helpers
    - CSV helpers
    - Directory creation
    - File discovery
    - Health checks
    - Output listing
    """

    def __init__(self, service_name: str):
        self.service_name = service_name

        # Ensure required folders exist
        Paths.create_directories()

        # Logger
        self.logger = get_logger(service_name)

    # ==========================================================
    # Logging Helpers
    # ==========================================================

    def log_info(self, message: str) -> None:
        self.logger.info(message)

    def log_warning(self, message: str) -> None:
        self.logger.warning(message)

    def log_error(self, message: str) -> None:
        self.logger.error(message)

    # ==========================================================
    # JSON Utilities
    # ==========================================================

    @staticmethod
    def load_json(path: Path) -> Dict[str, Any]:
        """
        Load a JSON file.

        Raises
        ------
        FileNotFoundError
            If the file does not exist.
        """

        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    @staticmethod
    def save_json(data: Dict[str, Any], path: Path) -> None:
        """
        Save dictionary as JSON.
        """

        path.parent.mkdir(parents=True, exist_ok=True)

        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)

    # ==========================================================
    # CSV Utilities
    # ==========================================================

    @staticmethod
    def load_csv(path: Path, **kwargs) -> pd.DataFrame:
        """
        Load CSV into DataFrame.
        """

        return pd.read_csv(path, **kwargs)

    @staticmethod
    def save_csv(df: pd.DataFrame, path: Path, **kwargs) -> None:
        """
        Save DataFrame as CSV.
        """

        path.parent.mkdir(parents=True, exist_ok=True)

        df.to_csv(path, index=False, **kwargs)

    # ==========================================================
    # File Utilities
    # ==========================================================

    @staticmethod
    def file_exists(path: Path) -> bool:
        return path.exists()

    @staticmethod
    def ensure_directory(path: Path) -> None:
        path.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def list_files(directory: Path, pattern: str = "*") -> List[Path]:
        """
        List files matching pattern.
        """

        if not directory.exists():
            return []

        return sorted(directory.glob(pattern))

    # ==========================================================
    # Output Utilities
    # ==========================================================

    def get_output_directory(self) -> Path:
        """
        Returns service output directory.

        outputs/
            underwriting/
            pricing/
            lapse/
            portfolio/
        """

        output_dir = Paths.OUTPUT_DIR / self.service_name

        output_dir.mkdir(parents=True, exist_ok=True)

        return output_dir

    def list_outputs(self) -> List[Dict[str, Any]]:
        """
        List output files generated by this service.
        """

        output_dir = self.get_output_directory()

        outputs = []

        for file in sorted(output_dir.iterdir()):
            if file.is_file():
                outputs.append({
                    "name": file.name,
                    "size_kb": round(file.stat().st_size / 1024, 2),
                    "path": str(file),
                })

        return outputs

    # ==========================================================
    # Metadata
    # ==========================================================

    def service_metadata(self) -> Dict[str, Any]:
        """
        Returns basic service information.
        """

        return {
            "service": self.service_name,
            "output_directory": str(self.get_output_directory()),
            "available_outputs": len(self.list_outputs()),
        }

    # ==========================================================
    # Health Check
    # ==========================================================

    def health_check(self) -> Dict[str, Any]:
        """
        Performs a basic service health check.
        """

        output_dir = self.get_output_directory()

        health = {
            "service": self.service_name,
            "status": "healthy",
            "output_directory_exists": output_dir.exists(),
            "log_directory_exists": Paths.LOG_DIR.exists(),
            "output_files": len(self.list_outputs()),
        }

        return health

    # ==========================================================
    # Pretty Summary
    # ==========================================================

    def summary(self) -> Dict[str, Any]:
        """
        Generic service summary.
        """

        return {
            "metadata": self.service_metadata(),
            "health": self.health_check(),
            "outputs": self.list_outputs(),
        }

    # ==========================================================
    # Placeholder Methods
    # ==========================================================

    def run_pipeline(self):
        raise NotImplementedError(
            f"{self.__class__.__name__} must implement run_pipeline()."
        )

    def get_metrics(self):
        raise NotImplementedError(
            f"{self.__class__.__name__} must implement get_metrics()."
        )

    def dashboard_data(self):
        raise NotImplementedError(
            f"{self.__class__.__name__} must implement dashboard_data()."
        )
